openapi: 3.0.0
info:
  title: API de Zapatillas
  description: API para gestionar colección de zapatillas.
  version: 1.0.0

servers:
  - url: http://localhost:3000
    description: Servidor local

paths:
  /zapatillas:
    get:
      summary: Obtener todas las zapatillas
      responses:
        '200':
          description: Lista de zapatillas
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Zapatillas encontradas con éxito"
                  statusCode:
                    type: integer
                    example: 200
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Zapatilla'
        '404':
          description: No se encontraron zapatillas
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Error interno del servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /zapatillas/{id}:
    get:
      summary: Obtener una zapatilla por ID
      parameters:
        - name: id
          in: path
          required: true
          description: ID de la zapatilla a obtener
          schema:
            type: string
      responses:
        '200':
          description: Zapatilla encontrada
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  statusCode:
                    type: integer
                  data:
                    $ref: '#/components/schemas/Zapatilla'
        '404':
          description: No se encontró la zapatilla
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Error del servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    put:
      summary: Actualizar una zapatilla por ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                brand:
                  type: string
                status:
                  type: string
      responses:
        '200':
          description: Zapatilla actualizada con éxito
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  statusCode:
                    type: integer
                  data:
                    $ref: '#/components/schemas/Zapatilla'
        '404':
          description: No se encontró la zapatilla
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Error del servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    delete:
      summary: Eliminar una zapatilla por ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Zapatilla eliminada
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  statusCode:
                    type: integer
                  data:
                    $ref: '#/components/schemas/Zapatilla'
        '404':
          description: No se encontró la zapatilla
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Error del servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /zapatillas/create:
    post:
      summary: Crear una nueva zapatilla
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ZapatillaInput'
      responses:
        '201':
          description: Zapatilla creada
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  statusCode:
                    type: integer
                  data:
                    $ref: '#/components/schemas/Zapatilla'
        '400':
          description: Error de validación
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Error del servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /zapatillas/admin/perma/{id}:
    delete:
      summary: Eliminar permanentemente una zapatilla
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Zapatilla eliminada
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  statusCode:
                    type: integer
                  data:
                    $ref: '#/components/schemas/Zapatilla'
        '404':
          description: No encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Error interno
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /zapatillas/admin/restore/{id}:
    delete:
      summary: Restaurar una zapatilla
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Zapatilla restaurada
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  statusCode:
                    type: integer
                  data:
                    $ref: '#/components/schemas/Zapatilla'
        '404':
          description: No encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Error interno
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /zapatillas/brand/{brand}:
    get:
      summary: Obtener zapatillas por marca
      parameters:
        - name: brand
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Zapatillas por marca
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Zapatilla'
        '404':
          description: No encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Error interno
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /zapatillas/status/{status}:
    get:
      summary: Obtener zapatillas por estado
      parameters:
        - name: status
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Zapatillas por estado
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Zapatilla'
        '404':
          description: No encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Error interno
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /zapatillas/cantidad/status/{status}:
    get:
      summary: Contar zapatillas por estado
      parameters:
        - name: status
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Cantidad de zapatillas encontradas
          content:
            application/json:
              schema:
                type: object
                properties:
                  cantidad:
                    type: integer
        '404':
          description: No encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Error interno
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    Zapatilla:
      type: object
      properties:
        id:
          type: string
        brand:
          type: string
        colorway:
          type: array
          items:
            type: string
        marketValue:
          type: number
        releaseYear:
          type: number
        status:
          type: string
        isActive:
          type: boolean

    ZapatillaInput:
      type: object
      required:
        - model
        - brand
        - colorway
        - marketValue
        - releaseYear
        - status
      properties:
        model:
          type: string
        brand:
          type: string
        colorway:
          type: array
          items:
            type: string
        marketValue:
          type: number
        releaseYear:
          type: number
        status:
          type: string

    ErrorResponse:
      type: object
      properties:
        message:
          type: string
        statusCode:
          type: integer
